//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccar
{
    using System;
    using System.Collections.Generic;
    
    public partial class actionLayoutDoneView
    {
        public int Id { get; set; }
        public string Initiator { get; set; }
        public System.DateTime OriginationDate { get; set; }
        public string TaskDescription { get; set; }
        public string Reason { get; set; }
        public string Responsible { get; set; }
        public System.DateTime TargetDate { get; set; }
        public string Progress { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public int Status { get; set; }
    }
}
