//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccar
{
    using System;
    using System.Collections.Generic;
    
    public partial class actionsMeetings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public actionsMeetings()
        {
            this.AttendanceMeetings = new HashSet<AttendanceMeetings>();
        }
    
        public int id { get; set; }
        public int idReason { get; set; }
        public System.DateTime originationDate { get; set; }
        public int initiatorId { get; set; }
        public string attendanceList { get; set; }
    
        public virtual reasons reasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceMeetings> AttendanceMeetings { get; set; }
    }
}
