//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccar
{
    using System;
    using System.Collections.Generic;
    
    public partial class actionViewCustom
    {
        public int id { get; set; }
        public string reason { get; set; }
        public string problem { get; set; }
        public string Initiator { get; set; }
        public Nullable<System.DateTime> originationDate { get; set; }
        public Nullable<System.DateTime> targetDate { get; set; }
        public Nullable<System.DateTime> completionDate { get; set; }
        public string responsible { get; set; }
        public string progressValue { get; set; }
        public Nullable<int> Status { get; set; }
        public int idReason { get; set; }
    }
}
