//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ccarMeetingMinutesEntities : DbContext
    {
        public ccarMeetingMinutesEntities()
            : base("name=ccarMeetingMinutesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MeetingMinutesAttendanceList> MeetingMinutesAttendanceList { get; set; }
        public virtual DbSet<MeetingMinutesAttendanceStatus> MeetingMinutesAttendanceStatus { get; set; }
        public virtual DbSet<meetingMinutesDates> meetingMinutesDates { get; set; }
        public virtual DbSet<MeetingMinutesPriority> MeetingMinutesPriority { get; set; }
        public virtual DbSet<MeetingMinutesProjects> MeetingMinutesProjects { get; set; }
        public virtual DbSet<MeetingMinutesProtocol> MeetingMinutesProtocol { get; set; }
        public virtual DbSet<MeetingMinutesStatus> MeetingMinutesStatus { get; set; }
        public virtual DbSet<MeetingMinutesTypeOfSubject> MeetingMinutesTypeOfSubject { get; set; }
        public virtual DbSet<mMusers> mMusers { get; set; }
        public virtual DbSet<mmDatesView> mmDatesView { get; set; }
    }
}
