//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccar
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingsView
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ProjectName { get; set; }
    }
}
