//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccar
{
    using System;
    using System.Collections.Generic;
    
    public partial class meetingMinutesDates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public meetingMinutesDates()
        {
            this.MeetingMinutesAttendanceList = new HashSet<MeetingMinutesAttendanceList>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> projectId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingMinutesAttendanceList> MeetingMinutesAttendanceList { get; set; }
        public virtual MeetingMinutesProjects MeetingMinutesProjects { get; set; }
    }
}
