//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccar
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingMinutesProtocol
    {
        public int id { get; set; }
        public int projectId { get; set; }
        public Nullable<int> priorityId { get; set; }
        public Nullable<System.DateTime> originationDate { get; set; }
        public Nullable<int> typeOfSubjectId { get; set; }
        public string Problem { get; set; }
        public Nullable<int> responsibleId { get; set; }
        public string support { get; set; }
        public Nullable<System.DateTime> targetDate { get; set; }
        public Nullable<int> statusId { get; set; }
        public string comments { get; set; }
    
        public virtual MeetingMinutesPriority MeetingMinutesPriority { get; set; }
        public virtual MeetingMinutesProjects MeetingMinutesProjects { get; set; }
        public virtual MeetingMinutesProtocol MeetingMinutesProtocol1 { get; set; }
        public virtual MeetingMinutesProtocol MeetingMinutesProtocol2 { get; set; }
        public virtual MeetingMinutesStatus MeetingMinutesStatus { get; set; }
        public virtual MeetingMinutesTypeOfSubject MeetingMinutesTypeOfSubject { get; set; }
        public virtual mMusers mMusers { get; set; }
    }
}
